import:
 - ~/.config/alacritty/themes/gruvbox_dark.yaml
 - ~/.config/alacritty/components/font.yaml
 - ~/.config/alacritty/components/cursor.yaml
 - ~/.config/alacritty/components/general.yaml
 - ~/.config/alacritty/components/key_bindings.yaml
 - ~/.config/alacritty/components/hints.yaml
