# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x282828'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  cursor:
    text: '#272727'
    cursor: '#a89984'

  vi_mode_cursor:
    text: '#272727'
    cursor: '#98971a'

  search:
    matches:
      foreground: '#272727'
      background: '#98971a'

    focused_match:
      foreground: '#272727'
      background: '#fabd2f'

    footer_bar:
      background: '#b16286'
      foreground: '#272727'

  hints:
    start:
      foreground: '#010816'
      background: '#E99440'

    end:
      foreground: '#E99440'
      background: '#010816'

  line_indicator:
    foreground: None
    background: None

  selection:
    text: CellBackground
    background: CellForeground

  normal:
    black:   '#272727'
    red:     '#ff3333'
    green:   '#b8cc52'
    yellow:  '#e6c446'
    blue:    '#36a3d9'
    magenta: '#f07078'
    cyan:    '#95e5cb'
    white:   '#ffffff'

  transparent_background_colors: false
