#!/usr/bin/perl

use strict;
use warnings;
use utf8;

# otherwise we get in console "Wide character in print at"
binmode(STDOUT, ':utf8');

# my $acpi;
my $upower;
my $percent;
my $bat_state;
my $status;
my $ac_adapt;
my $full_text;
my $short_text;
my $label = '😅';
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;
my $color = '#ffffff';
my $color_text = '#ffffff';

open (UPOWER, "upower -i /org/freedesktop/UPower/devices/battery_BAT$bat_number | grep 'percentage' |") or die;
$upower = <UPOWER>;
close(UPOWER);

# fail on unexpected output
if ($upower !~ /:          (\d+)%/) {
	die "$upower\n";
}

$percent = $1;
$full_text = "$percent%";

open (BAT_STATE, "upower -i /org/freedesktop/UPower/devices/battery_BAT$bat_number | grep 'state' |") or die;
$bat_state = <BAT_STATE>;
close(BAT_STATE);

if ($bat_state !~ /:               (\w+)/) {
	die "$bat_state\n";
}
$status = $1;

if ($percent < 10) {
  $color = '#cc241d';
  $color_text = '#fb4934';
} elsif ($percent < 50) {
	$color = "#d65d0e";
	$color_text = "#fe8019";
} elsif ($percent < 80) {
  $color = '#d79921';
  $color_text = '#b57614';
} else {
  $color = '#98971a';
	$color_text = '#79740e';
}

if ($status eq 'discharging') {
	if ($percent < 5) {
		systemctl poweroff
	} elsif ($percent < 10) {
  	$label = '󱃍';
	} elsif ($percent < 20) {
  	$label = '󰁺';
	} elsif ($percent < 30) {
  	$label = '󰁻';
	} elsif ($percent < 40) {
  	$label = '󰁼';
	} elsif ($percent < 50) {
  	$label = '󰁽';
	} elsif ($percent < 60) {
  	$label = '󰁾';
	} elsif ($percent < 70) {
  	$label = '󰁿';
	} elsif ($percent < 80) {
  	$label = '󰂀';
	} elsif ($percent < 90) {
  	$label = '󰂁';
	} elsif ($percent < 95) {
  	$label = '󰂂';
	} else {
  	$label = '󰁹';
	}
} elsif ($status eq 'charging') {
	if ($percent < 10) {
  	$label = '󰢟';
	} elsif ($percent < 20) {
  	$label = '󰢜';
	} elsif ($percent < 30) {
  	$label = '󰂆';
	} elsif ($percent < 40) {
  	$label = '󰂇';
	} elsif ($percent < 50) {
  	$label = '󰂈';
	} elsif ($percent < 60) {
  	$label = '󰢝';
	} elsif ($percent < 70) {
  	$label = '󰂉';
	} elsif ($percent < 80) {
  	$label = '󰢞';
	} elsif ($percent < 90) {
  	$label = '󰂊';
	} elsif ($percent < 95) {
  	$label = '󰂋';
	} else {
  	$label = '󰂅';
  }
} elsif ($status eq 'fully') {
 	$label = '󰂄';
}

# print text
print "${full_text}\n";
