#!/usr/bin/perl

use strict;
use warnings;
use utf8;

# otherwise we get in console "Wide character in print at"
binmode(STDOUT, ':utf8');

my $list_sinks = `pactl list sinks`;

# Get the volume level
# Run the pactl command and capture the output
my $command = 'pactl get-sink-volume @DEFAULT_SINK@';
my $output = `$command`;

# Extract the volume percentage using a regular expression
my ($volume) = $output =~ /(\d+)%/;
my $color_text = '#b16270';
my $color = '#b1628F';
my $icon = '';

# Calculate the number of blocks for the volume icon
if ($list_sinks =~ /Mute: yes/) {
  $icon = '󰖁';
  $color = "#a89984";
  $color_text = "#928374";
} elsif ($volume == 0) {
  $icon = '󰸈';
} elsif ($volume < 20) {
  $icon = '';
} elsif ($volume < 50) {
  $icon = '';
} elsif ($volume < 80) {
  $icon = '󰕾';
}

## Echo the volume icon and percentage
print "<span foreground='${color}'> <span size='large'>${icon}</span> <span foreground='${color_text}'>${volume}%</span></span>";
