env:
  TERM: xterm-256color

window:
  padding:
    x: 20
    y: 0
  opacity: 1
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
  dynamic_title: true
  dynamic_padding: true

  decorations: full

live_config_reload: true
